### ISSUE TITLE
Provide an example test in the readme

### ISSUE THREAD

**Issue by evantahler** [alexeyraspopov/jest-webdriver#2]
It would be very helpful to see an example test in the readme.

I've added one here https://blog.evantahler.com/testing-javascript-applications-with-selenium-async-await-and-jest-7580ed074f2b

**Comment by alexeyraspopov** [comment]
I just saw your article earlier today. Great work, thank you for doing this!

I'm trying to find time and work on complete documentation and guides (i.e. work in progress [Patterns Guideline](https://github.com/alexeyraspopov/jest-webdriver/blob/master/docs/WritingTests.md)). So far, the repo only has [basic-testcase](https://github.com/alexeyraspopov/jest-webdriver/tree/master/examples/basic-testcase) demo that covers coding part.

I'll put your article to README since it provides pretty straightforward and user-friendly examples and explanation.

Thanks!
